name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: install
        run: cd packages/vscode-scripts && npm ci
      - name: Start dev server
        uses: codercom/code-server:latest
        run: /source --auth none --disable-telemetry --disable-workspace-trust
        with:
          container_name: vscodeExtension
          ports:
            - 8080:8080
          volumes:
            - .:/source
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run package
          config-file: cypress/cypress.config.ts
