name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: install
        run: cd packages/vscode-scripts && npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run package
          start: docker-compose -f ./packages/vscode-scripts/docker-compose.yml up -d && docker exec vscodeExtension code-server --install-extension /source/vscode-starter-1.0.0.vsix
          config-file: cypress/cypress.config.ts
