name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    # Cypress Docker image from https://hub.docker.com/r/cypress
    # with browsers pre-installed
    container:
      image: cypress/browsers:latest
      options: --user 1001
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Compose
        run: service docker start
      - name: install
        run: cd packages/vscode-scripts && npm ci
      - name: Start code-server and wait
        run: npm run code-server-up && wait-on http://localhost:8080
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: npm run package
          start: echo "Cypress tests are ready to run"
          config-file: cypress/cypress.config.ts